# Generated by Django 4.2.16 on 2026-07-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("inscription", "Inscription"),
                            ("inscription_accepted", "Inscription acceptee"),
                            ("inscription_rejected", "Inscription rejetee"),
                            ("message", "Message"),
                            ("teacher_added", "Enseignant ajoute"),
                            ("system", "Systeme"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'col"."activity_log',
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("Premiere inscription", "Premiere inscription"),
                            ("Reinscription", "Reinscription"),
                        ],
                        max_length=50,
                    ),
                ),
                ("student_status", models.CharField(max_length=50)),
                (
                    "school_level",
                    models.CharField(
                        choices=[
                            ("Maternelle", "Maternelle"),
                            ("ECOFO", "ECOFO"),
                            ("Lycee Technique", "Lycee Technique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("student_first_name", models.CharField(max_length=100)),
                ("student_last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Fille", "Fille"), ("Garcon", "Garcon")],
                        max_length=20,
                    ),
                ),
                ("requested_class", models.CharField(max_length=100)),
                (
                    "previous_school",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("guardian_name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("Pere", "Pere"),
                            ("Mere", "Mere"),
                            ("Tuteur", "Tuteur"),
                            ("Autre responsable", "Autre responsable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField()),
                ("school_year", models.CharField(max_length=20)),
                (
                    "documents",
                    models.CharField(
                        choices=[
                            ("Bulletin uniquement", "Bulletin uniquement"),
                            (
                                "Bulletin + acte de naissance",
                                "Bulletin + acte de naissance",
                            ),
                            ("Dossier complet", "Dossier complet"),
                            ("Aucun pour le moment", "Aucun pour le moment"),
                        ],
                        default="Bulletin uniquement",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("En revision", "En revision"),
                            ("Acceptee", "Acceptee"),
                            ("Rejetee", "Rejetee"),
                        ],
                        default="En attente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'col"."inscription',
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": 'col"."message',
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'col"."school_config',
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Fille", "Fille"), ("Garcon", "Garcon")],
                        max_length=20,
                    ),
                ),
                (
                    "school_level",
                    models.CharField(
                        choices=[
                            ("Maternelle", "Maternelle"),
                            ("ECOFO", "ECOFO"),
                            ("Lycee Technique", "Lycee Technique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("current_class", models.CharField(max_length=100)),
                ("guardian_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField()),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'col"."student',
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("Actif", "Actif"), ("En conge", "En conge")],
                        default="Actif",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'col"."teacher',
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
